src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="cette email n'est plus disponible !")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function __toString()
    {
        return $this->Nom.' '.$this->Prenom;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;
use App\Entity\Articles;



class ProfileController extends AbstractController
{
    /**
     * @Route("/profile", name="app_profile")
     */
    public function index(): Response
    {
        $repo = $this->getDoctrine()->getRepository(Articles::class);      
        $articles = $repo->findAll();

        return $this->render('profile/index.html.twig', [
            'articles' => $articles,
        ]);
    }
}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile utilisateur{% endblock %}

{% block body %}
<body class="hold-transition sidebar-mini layout-fixed" >
    <div class="wrapper">

<div class="content-wrapper" style="min-height: 213px;">
            <!-- Content Header (Page header) -->
            <div class="content-header">
            <div class="container-fluid">

<section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-3">

{#-------------------------------profile-----------------------------------------#}
            <!-- Profile Image -->
            <div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                  <img class="profile-user-img img-fluid img-circle" src="asset/blog/images/profile.png" alt="User profile picture">
                </div>

                <h3 class="profile-username text-center">{{app.User.Nom}} {{app.User.prenom}}</h3>

                <p class="text-muted text-center">{{app.User.email}}</p>

              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <!-- About Me Box -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Apropos de moi</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <strong><i class="fas fa-book mr-1"></i> Education</strong>

                <p class="text-muted">
                  None
                </p>

                <hr>

                <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

                <p class="text-muted">None</p>

                <hr>

                <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>

                <p>None</p>

                <hr>

                <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>

                <p class="text-muted">None</p>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
          <div class="col-md-9">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Publication</a></li>
                  
                </ul>
              </div><!-- /.card-header -->

{#-------------------------------------------la publication recent-------------------------------#}
      {% for article in articles %}
              <div class="card-header">
                <div class="user-block">
                  <img class="img-circle" src="asset/blog/images/profile.png" alt="User Image">
                  <span class="username"><a href="#">{{article.auteur}}</a></span>
                  <span class="description">Publier le - {{article.createdAt | date('d/m/y H:m:s')}}</span>
                </div>
              </div>  
        <h1 class="title p-2">{{ article.title}}</h1>
        <div class="card-body" style="display: block;">
                <img class="img-fluid pad" src="asset/blog/images/{{article.image}}" alt="{{article.title}}">

                <p>{{article.contenu | raw }}</p>
                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
                <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
                <span class="float-right text-muted">127 likes - 3 comments</span>
              </div>    

        <div class="card-footer card-comments" style="display: block;">
                <div class="card-comment">
                  <!-- User image -->
                  <img class="img-circle img-sm" src="AdminLte/dist/img/user3-128x128.jpg" alt="User Image">

                  <div class="comment-text">
                    <span class="username">
                      Maria Gonzales
                      <span class="text-muted float-right">8:00 PM Today</span>
                    </span><!-- /.username -->
                    It is a long established fact that a reader will be distracted
                    by the readable content of a page when looking at its layout.
                  </div>
                  <!-- /.comment-text -->
                </div>
                <!-- /.card-comment -->

                <div class="card-footer" style="display: block;">
                
                {% if app.User %}
                   {# {{ form_start(commentsForm) }}
                
                  <img class="img-fluid img-circle img-sm" src="AdminLte/dist/img/user4-128x128.jpg" alt="Alt Text">
                  <!-- .img-push is used to add margin to elements next to floating images --> #}
                  <div class="img-push">
                  {# {{form_label(commentsForm.email, 'Votre Email', {'attr': {'style': 'form-label inline-block mb-2 text-gray-700'}} ) }}
                  {{form_row(commentsForm.email)}}
                  {{form_label(commentsForm.nickname, 'Votre Pseudo', {'attr': {'style': 'form-label inline-block mb-2 text-gray-700'}} ) }}
                  {{form_row(commentsForm.nickname)}}
                  {{form_label(commentsForm.content, 'Nouveau commentaire', {'attr': {'style': 'form-label inline-block mb-2 text-gray-700'}} ) }}
                  {{form_row(commentsForm.content, {'attr': {'class': 'form-control form-control-sm font-normal text-gray-700 padding border border-solid', 'placeholder': 'clicker ici pour poster votre commentaire...'} } ) }}
                 #}
                    <input type="text" class="form-control form-control-sm" placeholder="Press enter to post comment">
                
                    <button class="btn inline-block px-6 py-2.5 btn-primary text-white rounded hover:bg-blue" style="margin:10px 0" type="submit">
                        Poster mon commentaire
                    </button>
                    
                  </div>
                  {# {{ form_end(commentsForm) }} #}
                {% endif %} 
                
                
              </div>
              </div>
              {% endfor %}
{#------------------------------------------------fin de publication---------------------------#}

          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>

    </div>
    </div>
    </div>

    </div>
    </body>
{% endblock %}